### ISSUE TITLE
Asset does not include all features

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#1102]
I expected the [https://github.com/jqnatividad/qsv/releases/download/0.108.0/qsv-0.108.0-x86_64-apple-darwin.zip](https://github.com/jqnatividad/qsv/releases/download/0.108.0/qsv-0.108.0-x86_64-apple-darwin.zip) to include the `to` sub command, but it doesn't

Did I miss something?

**Comment by jqnatividad** [comment]
I'm afraid we still use GitHub's action runners to compile the x86_64-apple-darwin build, and GH's Action Runner VMs are just not big enough and we run out of memory/disk space.

I currently don't have access to a larger Intel-powered Mac, so I don'y have the option to create a self-hosted Action Runner, similar to what I did for the arm64-apple-darwin build.

In the next release, I'll add another workflow to generate two flavors of qsv to include in the x86_64-apple-darwin zip - one with polars, and another one with the to feature enabled.

**Comment by ondohotola** [comment]
I compiled it myself which works fine.

**Comment by jqnatividad** [comment]
Good to know... for the next release, I'll also check if I can cross-compile the x86_64-apple-darwin build from the Apple Silicon self-hosted action runner, so we don't need to have qsv binary subvariants

**Comment by ondohotola** [comment]
Great, I would prefer to have one version only (the kitchen sink without Python)

**Comment by polarathene** [comment]
> just not big enough and we run out of memory/disk space.

FWIW, is `lto = true` really necessary? Have you benched it compared to `lto = "thin"`? When compiling from source this was causing over 10GB of RAM required to build.

Since these releases are already being minimized in feature availability, you could consider full featured builds if they're possible with `lto = "thin"` instead which should require far less memory, build faster and have minimal perf loss from what I understand?

I think that is preferable for making `qsv` more accessible to try, and deferring users to compile from source with `lto = true` if they want to squeeze out more performance? (_other perf improvements like CPU features are something generic releases can't really opt-in for, so this seems like a fair trade off_)
