### ISSUE TITLE
`diff`: only show headers when there are differences

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#1326]
@janriemer , I think it'd be great if `qsv diff` behaves like the diff CLI command, which produces no output when files are identical.

**Comment by janriemer** [comment]
Hey @jqnatividad :wave: 

this definitely sounds like a useful feature to have! :+1: Thank you for bringing this up! I can imagine a use-case, where one can more easily check via a script if there is a diff or not, when there is no output, when files are identical.

At first, I was a bit worried that this would make composing diff results together more difficult:

Scenario: comparing files A and B and then comparing that result (let's call it AB) with C, where all files have headers - all in _one_ command

=> It would be impossible to configure `diff`'s argument options for AB, because we don't know in advance, whether A and B are equal - or, in other words: we don't know, whether AB will have headers applied to it or not.

### Suggested solution
After thinking about this a little more, though, I think we can __generalize__ this feature to the following:

**=> Let's provide an option that configures, whether the diff result should output headers or not (independent of whether both files are equal).**

The [current behavior](https://github.com/jqnatividad/qsv/blob/c71cd16a22f729a074a2a8d59020eba4cc8d7281/src/cmd/diff.rs#L174-L197) (without this option) is: use headers, [when at least one file has headers](https://github.com/jqnatividad/qsv/blob/c71cd16a22f729a074a2a8d59020eba4cc8d7281/src/cmd/diff.rs#L174-L197).

### Remaining open questions (and possible solutions)
_Note: the names that are used for cli options here probably won't be the exact names in the final implementation._
- :warning:  What should happen, when we specify `header-in-result=true`, but _none of the compared files have headers_? Where should we draw the header names from?

Possible solutions:
- ✅ use default column names, like `column` (this value should also be configurable) and number them: `column1, column2, etc.` _=> this is my preferred solution (for the first iteration)_
- ✅ Allow to specify the column names directly, like `header-names-in-result='Foo,Bar,Baz,...'`
  - :warning: this is more error-prone: e.g. what happens, when too few or too many header names are specified (when the number of specified header names don't match the actual number of columns in the CSV)?

---------------------------
What do you think about this? I'm glad, we can improve `diff` together and make it the best it can be! 😊 :rocket:

**Comment by jqnatividad** [comment]
Hi @janriemer! 👋 

Thanks for giving this feature request a lot of thought.

Let's go with your preferred solution. The one thing I'd bring to your attention is how to `rename` handles a similar situation.

For consistency, perhaps, `diff` should follow what `rename` does with the `_all_generic` magic value?

https://github.com/jqnatividad/qsv/blob/master/src/cmd/rename.rs

WDYT?

**Comment by janriemer** [comment]
Hi @jqnatividad, 

just want to let you know that I'm actively working on this. First tests seem promising! :slightly_smiling_face: 

Thank you also for the hint regarding `rename` and `_all_generic`. :+1:  I'm using this now, when _neither input files have headers_. The only thing I'm struggling with here is: __how to know the number of columns that need to be generated?__

I think we need to expose the number of columns somehow in `csv-diff` crate - more precisely in [`DiffByteRecords`](https://docs.rs/csv-diff/0.1.0-beta.4/csv_diff/diff_result/struct.DiffByteRecords.html) (which [is used by `diff` command](https://github.com/jqnatividad/qsv/blob/a6f7ed92e20c579e341b00ae8329e66da84406cf/src/cmd/diff.rs#L142)).

Nothing, we can't solve, though. :wink: 

I'll probably give another update on Wednesday or next weekend. :crossed_fingers:

**Comment by janriemer** [comment]
Hi @jqnatividad :wave: 

another update: [an MR for the crate `csv-diff` is now in review (by me)](https://gitlab.com/janriemer/csv-diff/-/merge_requests/26). Once merged, it will allow `csv-diff` to:
- get the number of columns that a `DiffByteRecord` will have
   - this pretty much includes all cases, like
      - when there is no diff, but at least one CSV has headers
      - when there is a diff, but no headers
      - etc.
- get at the headers in the diff result (if originally provided via `has_headers` flag in `csv`)
   - this will allow us to more easily output the headers in the result

After the acceptance of the MR, I'll prepare a new release of `csv-diff` (it will be 0.1.0 - first non-alpha/-beta release (:tada:)) and we can use the new functionality for this enhancement in `diff`. Very exciting! :sparkles: :relaxed: 

### Next steps
- [ ] Merge MR in `csv-diff`
- [ ] Release new version 0.1.0 of `csv-diff`
- [ ] Implement this enhancement in `diff` and create a PR

---------------------------
### Some anecdote (not important, only if you're interested)

Providing the above functionality in `csv-diff` hasn't been _that_ easy, but it has shown me a very good path on how to provide similar functionality in the future (in the past, I've tried similar things, but failed). What I mean by that is, that it is almost like "sniffing" the first rows of the CSVs now, which is difficult when the goal is to do everything in a single pass, due to parsing and diffing happening in different threads (I know that there is the `qsv-sniffer` crate, but because of what I've just mentioned, I'm not sure it is suitable for `csv_diff`).

**Comment by jqnatividad** [comment]
Thanks for the update @janriemer !

I look forward to merging the first non-beta powered `diff` powered by `csv-diff`!

And I can emphatize with your journey with it - I've gone down many dead-ends with qsv myself, and even ended up reverting some code several times and removing features (like auto-transcoding to utf-8).

It's interesting you mention `qsv-sniffer` as that was something I adapted from `csv-sniffer` and the Viterbi algorithm at its heart is still somewhat opaque to me, which prevents me from really making it a bulletproof sniffer, as there are still some valid CSVs that it sometimes fails to sniff. 

BTW, speaking of `sniff`, have you considered adding an additional mode to `diff` to return JSON metadata about the diff rather than the diff result?

I do this in several commands in addition to `sniff` - `excel`, `safenames`, `sortcheck` & `validate`.

qsv is meant to be used in pipelines as well, and having machine-readable JSON would be great!

**Comment by janriemer** [comment]
Hey @jqnatividad 

sorry for the late reply. 😳 The PR for this issue is ready at #1395! :tada: 

Thank you for sharing your experience of your journey with qsv and the difficulties you've encountered along the way. qsv is a very complex project and I'm very impressed by what you've achieved so far! :tophat: 

Yeah, I can imagine `sniff` being difficult. :woozy_face: 

Yes, thank you for the idea regarding JSON output. :+1: It is on my list of TODOs, but "unfortunately" this list gets longer and longer. :smile: I'd like to have some other things take priority right now, that are more kind of _stabilizations_, like:
- deal with CSVs that have headers, but have different ordering
- deal with CSVs that are `flexible`
- provide a cryptographically secure version for diffing (currently xxhash, a 128-bit non-crypto-hash, is used) and make it configurable with cargo features which hash to use
- refactor module organization and cargo features, so that cargo features are all compatible with each other

But I'll see what I can do. :wink: With `serde` this _might_ be relatively easy, but I can't really tell right now.
