### ISSUE TITLE
Extended --group for qsv cat rowskey?

### ISSUE THREAD

**Issue by tmtmtmtm** [jqnatividad/qsv#1506]
The ability to add a source filename as a column with `qsv cat rowskey --group` is very useful, but I'm often dealing with a scenario where I have multiple parallel directories (e.g. one directory per source; or one directory per month), each of which contains files with the same name. Currently, unless I've overlooked some option, `rowskey --group` can only give each of those the same value, but it would be very useful it could also handle this scenario.

Perhaps there could be an option to use the full path+filename, rather than only the stem?

**Comment by jqnatividad** [comment]
@tmtmtmtm , I changed `--group` from a boolean flag to a string option which allows you to specify different grouping value options beyond file stem.

Also tweaked `rowskey` to write records by row rather than by field, so performance should be faster as well. 

Closing this enhancement as complete,  Feel free to reopen if you have any issues.

**Comment by tmtmtmtm** [comment]
@jqnatividad that looks excellent - thank you!

**Comment by jqnatividad** [comment]
Hi @tmtmtmtm ,

Do you mind adding your use cases for qsv here?

https://github.com/jqnatividad/qsv/discussions/1529

We have big plans for qsv & qsv pro and having some background info would be great!
