### ISSUE TITLE
Invalid arguments or "--filename argument must contain one '{}'" on split function

### ISSUE THREAD

**Issue by papagunit** [jqnatividad/qsv#1584]
**Describe the bug**
It's unclear how the -s flag should be used with the split function, I keep getting errors. Can you provide an example of the syntax and how it's supposed to be used?

**To Reproduce**
qsv split -s 300 --filename Test{start}.csv '.\Filename.csv'
Returns:
usage error: The --filename argument must contain one '{}'.

qsv split -s 300 --filename Test{}.csv '.\Filename.csv'
Returns:
usage error: The --filename argument must contain one '{}'.

qsv split -s 300 --filename {}.csv '.\Filename.csv'
Returns:
usage error: Invalid arguments.

qsv split -s 300 --filename 'Test{start}.csv'  '.\Filename.csv'
Returns:
usage error: The --filename argument must contain one '{}'.

qsv split -s 300 --filename 'Test{}.csv'   '.\Filename.csv'
Returns:
io error: Cannot create a file when that file already exists. (os error 183)
Note, there are no other files with a similar name.

**Desktop (please complete the following information):**
 - OS: Powershell 5.1 on windows
 - qsv Version 0.122

**Comment by jqnatividad** [comment]
Hi @papagunit,

You'll need to specify the <outdir> parameter for it to work, i.e.:

`qsv split myoptputdir -s 300 --filename Test{}.csv '\.Filename.csv'`

Regardless, I'll improve the usage text with examples rather than linking to the tests, and add explicit error handling if the `outdir` arg is empty.
