### ISSUE TITLE
sqlp: not able to create a rigth parquet output

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#1647]
Hi,
I'm testing sqlp using this CSV: [Opendata2.csv.gz](https://github.com/jqnatividad/qsv/files/14501387/Opendata2.csv.gz)

I create a parquet output in this way

```
qsv sqlp -d ";" Opendata2.csv "select * from Opendata2" --format parquet --output data.parquet --compression zstd
```

I have a parquet output, but it seems that everything is in one column, that it was not useful to set the field separator using ` -d ";"`.

I'm using 'qsv 0.123.0-mimalloc-apply;fetch;foreach;python-3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0];to;polars-0.38.1;self_update-20-20;6.09 GiB-1.22 GiB-6.25 GiB-7.61 GiB (x86_64-unknown-linux-gnu compiled with Rust 1.76.0) compiled'

Thank you

![image](https://github.com/jqnatividad/qsv/assets/30607/36c1677e-5ae9-4484-a18e-af238b7f0520)

**Comment by jqnatividad** [comment]
Hi @aborruso , this is because the automatic `read_csv()` fast path optimization doesn't support custom delimiters.

The workaround is to enable the "--no-optimizations" so we skip the fast path optimization and read in the CSV first into the SQL context.  This mode will honor your `--delimiter` setting.

I'll add some additional checks for CSV parsing settings so it will automatically turn off optimization if a custom delimiter is specified.

**Comment by aborruso** [comment]
> Hi @aborruso , this is because the automatic `read_csv()` fast path optimization doesn't support custom delimiters.

Thank you very much.

I have a lot of CSV as this one and I would like to merge them. How to do it? Do I must use an .infile-list file?
If yes, [I'm not able to use it](https://github.com/jqnatividad/qsv/discussions/1645).
