### ISSUE TITLE
Can qsv reverse or sort column order?

### ISSUE THREAD

**Issue by vi** [jqnatividad/qsv#1864]
I see `qsv reverse` for reversing the rows, but don't see tools to shuffle columns around.

I wanted to workaround missing column sorting in [DuckDB's PIVOT](https://duckdb.org/docs/sql/statements/pivot.html) by postprocessing the file in qsv, but haven't found it in qsv either.

**Comment by jqnatividad** [comment]
`select` allows you to shuffle columns around...

It has several modes for "select"ing columns and moving, reordering, and suppressing columns.

Let me know if it works for you...

**Comment by vi** [comment]
Yes, it is close to what I wanted, especially with the reverse ranges. I need to know the number of columns in advance though to avoid `Selector index .. is out of bounds.`.

Suggested changes:

* `--ignore-missing` to skip invalid (i.e. out of range or non-existent) selectors. `--ignore-missing 999-1`  may be documented as a column reverser.
* `--sort` (or some special selector) to automatically sort columns by name (ideally with a numeric and [version]https://crates.io/crates/vsort) sort support).
* `--random` to shuffle columns.

This may make working with square-shaped data easier, avoiding `qsv transpose` steps.

**Comment by jqnatividad** [comment]
Great suggestions @vi . Will add them to the backlog...

**Comment by jqnatividad** [comment]
Implemented in #1867.

@vi , let me know how it works out for you.

**Comment by vi** [comment]
Thanks (though I have already moved on to next problems).

I would reconsider the UX before making a release - current scheme (especially the `9999` sentinel and fake `1` selector) looks ad-hoc. This is also a semver-breaking change (and a deviation from `xsv select`) because of the sentinel. Existing scripts relying on ability to select specific column may start suddenly producing wrong results facing a very wide CSV.

Sorting options should also be more universal. There should be underlying mechanism with `qsv sort`, so that adding more features to one would also automatically add options to `qsv select`.

**Comment by jqnatividad** [comment]
Thanks @vi for following up. To your points:
* I'll just introduce a special value ("#lastcol?) to indicate the last column instead of 9999. Though I doubt that aren't too many 9999 column wide CSVs, this is more verbose and literal.
* the `1` selector is just a dummy value - it could very well be ANY value. It's just there to satisfy the docopt parser. In the examples, I'll specify an obvious dummy selector value
* As for sorting options carrying over to other commands like `select`, `sort` is more of a traditional qsv/xsv command than `select` which is actually more of a suite-wide helper, that also gets exposed as a command (that's why it has a very small implementation as a command).  Traditional commands don't have the same suite-wide impact like `select`.
* I'll revisit `--ignore-missing`. I thought it was there primarily to support the last column requirement, but you're right that it does have its own merits.

**Comment by vi** [comment]
> I'll just introduce a special value ("#lastcol?) to indicate the last column instead of 9999. Though I doubt that aren't too many 9999 column wide CSVs, this is more verbose and literal.

This is better, though specifically `#` may be inconvenient to specify e.g. in Bash. Maybe `(-1)` can be made to mean last column (and `(-2)` the penultimate one and so on).

> the 1 selector is just a dummy value - it could very well be ANY value. It's just there to satisfy the docopt parser. In the examples, I'll specify an obvious dummy selector value

I expect sorting/shuffling to work not _instead_ of selection, but _after_ it. I.e. `qsv select 2- --sort` to throw away the first column and sort the rest ones.

> sort is more of a traditional qsv/xsv command than select which is actually more of a suite-wide helper, that also gets exposed as a command (that's why it has a very small implementation as a command).

I does not understand what is it about and what is distinction between a traditional and non-traditional commands.
