### ISSUE TITLE
qsvpdp-unknown-linux-musl is missing commands?

### ISSUE THREAD

**Issue by Dialga** [jqnatividad/qsv#2064]
**Describe the bug**
qsvpdp is missing the sqlp, luau, joinp commands

**To Reproduce**
As above.

**Expected behavior**
The unknown-linux-musl build to include the datapusher commands.

**Screenshots/Backtrace/Sample Data**
If applicable, add screenshots/backtraces/sample data to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - qsv Version 0.131.1

**Additional context**

**Comment by jqnatividad** [comment]
Last time I tried, `luau` would not cross-compile in the `unknown-linux-musl` platform and `sqlp` and `joinp` are not included in the `qsvdp` variants by design given how big they'll make the binary.

Also, in the current version, all the commands you cited are not used by DP+.

Regardless, you are free to specify to use an alternate qsv variant, even the full qsv prebuilt variant with DP+ by changing its configuration section in the CKAN ini file.

If you're using the prebuilt binaries, you may also want to install or compile from source using Arch Linux instead, to get a qsvpdp variant that works in Arch Linux.

As we use GitHub's action runners to create the prebuilts, the `musl` targets have to be cross-compiled as there are no native unknown-linux-musl action runners, and there are certain limitations when cross-compiling with Rust that forced me to exclude `luau` from the musl prebuilts.

I could have created a self-hosted, unknown-linux-musl action runner (as I did with Apple Silicon), but I do not have machines that run using that platform as we primarily target the latest Ubuntu LTS for all our work.

**Comment by jqnatividad** [comment]
@Dialga , I added the note as you suggested.

Feel free to open a PR to further wordsmith the note if required.
