### ISSUE TITLE
qsv schema does not work via stdin

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#298]
**Describe the bug**

If I run `cat tmp.csv | qsv schema -d ";"` I have `Failed to infer schema via stats and frequency: Input is empty.`.

**To Reproduce**

I have used this input file <https://gist.githubusercontent.com/aborruso/453e757f915c2d1708fc0e595538e495/raw/0214e4ab7f2af8f45e92f48bf176fe300c82d467/tmp.csv>

**Expected behavior**
To have the schema

**Desktop (please complete the following information):**
 - OS: Debian
 - qsv Version: qsv 0.48.1-mimalloc-apply;fetch;foreach;generate;lua;python;-8-8

Thank you

**Comment by jqnatividad** [comment]
Thanks for the report @aborruso. I looked into this, and it seems the root cause is that stdin is not seekable. 

We're calling `stats` and `frequency` from `schema`, and stdin works fine with `stats` the first time we read stdin, but it doesn't work with `frequency`further down as stdin has reached EOF.

I may have to create a temporary file from stdin instead of working with it directly for it to work.
