### ISSUE TITLE
BUG Python library not found on WSL2 Pengwin

### ISSUE THREAD

**Issue by eggbean** [jqnatividad/qsv#459]
I get this error on `qsv` from this zip file - [qsv-0.64.0-x86_64-unknown-linux-gnu.zip](https://github.com/jqnatividad/qsv/releases/download/0.64.0/qsv-0.64.0-x86_64-unknown-linux-gnu.zip)

    qsv: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

```
$ python3 --version
Python 3.9.2
```

`libpython3.9` is installed. `qsvnp` works fine.

**Desktop (please complete the following information):**
 - OS: Pengwin on WSL2 (based on Debian 11)
 - qsv Version 0.64

**Comment by jqnatividad** [comment]
Thanks for the report @eggbean .

Have you tried creating a softlink to libpython3.9 in the same directory where the qsv binary is?

**Comment by eggbean** [comment]
I did try making symlinks, but I couldn't get it working. I think I'll not use this on WSL.

**Comment by jqnatividad** [comment]
@eggbean , I simplified Python support (https://github.com/jqnatividad/qsv/pull/492).

It was my bad - I misinterpreted PyO3's `abi3` multiple python version support. I thought it applied to Rust binaries, it turns out multiple Python version support only applies if you're creating Python modules using Rust.

Anyway, in your case, this means installing/compiling from source if you still want to use qsv with Python 3.9 as qsv can support Python 3.6 and up.

`cargo install qsv --features all_full`

FYI, the pre-built qsv binaries now also target Python 3.10 (it was 3.8 before, and the reason why you were getting the shared library error).

There's a new section in the README about Python support if you want to find out more - https://github.com/jqnatividad/qsv#python

**Comment by eggbean** [comment]
Great, thanks. So you mean the next release binaries should work? The current version doesn't on WSL.

**Comment by jqnatividad** [comment]
Starting with the next release, the **prebuilt** qsv binaries will require the latest stable Python version - currently Python 3.10.

If you need to use an older version of Python, you will need to install/compile from source, making sure the Python development libraries are in place so qsv will be linked to the desired version of Python.

So it's still a no for your specific case - as you're running Python 3.9.2.

Starting with the next release, your options are:
* if you want to use the prebuilt qsv binaries
    * upgrade to Python 3.10
    * find a copy of libpython3.10 Python library and copy it to the same directory where the qsv binary is. "Bundling" python3.10 library works as qsv looks for the python library in the same directory it is first before looking elsewhere.
* manually install/compile qsv from source. qsv will use the current python version (it supports linking to Python 3.6 and up).

**Comment by eggbean** [comment]
Okay thanks. I think it will be easiest to have the library in the same directory as the binary. I don't understand why you are compiling the release binaries to require a newer version of python than what is available on most distros (RHEL/Debian) when it can be compiled with more relaxed requirements?

**Comment by jqnatividad** [comment]
Why 3.10? My goto Linux distro is the latest Ubuntu LTS, and in 22.04, the default python version is 3.10.

I don't really use RHEL and most of our clients use Ubuntu LTS...  anyways, you can always compile from source...

**Comment by eggbean** [comment]
Thanks for this information, but these issues seem to be easily resolved by putting the library file in the same directory as the release binary. Cheers.

**Comment by jqnatividad** [comment]
@eggbean , I'm actually exploring adding the python shared library to the qsv release zip file.
If there are no license limitations, it should be in the next release.

I'll also add a metadata file to the distribution zip, with info like the python version, the Rust compiler used, etc.

**Comment by eggbean** [comment]
Great, thanks.

**Comment by eggbean** [comment]
Hi again. My github action that I made for copying qsv files to a repository has failed, so I just wanted to know if there are no more armv7l binaries being made? It's not that important to me, as I am unlikely to use qsv on in that architecture.

Also, there does not seem to be any python library in the aarch64 zip file for Linux. The library in the x86_64 zip for Linux does not seem to have any effect when I run qsv with it in the same directory. This is not something that concerns me, as I will just use qsv on Linux machines rather than WSL, but I thought I should mention it.

**Comment by jqnatividad** [comment]
Hi @eggbean,
Yes, I'm dropping that architecture for now as it was causing problems with packaging the cross-compiled pre-built binaries.
There were no qsv users I'm aware of for that architecture anyway.  Should there be some demand for it, perhaps I'll bring it back.

And yeah, Github's Action Runners are all x86_64 based and I couldn't figure out a way to get the python library for the target architecture when cross-compiling to other platforms.

When time permits, I do manual builds for Apple Silicon since my daily driver is an M1 Mac Mini, but I can't do that for the other architectures I don't have access to.
