### ISSUE TITLE
Please consider the qsv auto-update feature to be off by default. 

### ISSUE THREAD

**Issue by slonyik** [jqnatividad/qsv#482]
**Is your feature request related to a problem? Please describe.**
by default,  qsv upon its start tries to to connect on github.com to check for updates.
It is a nice convenience feature.
We use qsv with restricted NW and set `export QSV_NO_UPDATE=1` to skip the checks.

However with more ppl introduced to qsv the setting of that parameter (and resulting connect attempt) becomes a bit burden/problem :-/

Thus I would like to ask you to reconsider the current behaviour - connecting to github to check for updates 
and made it off/disabled by default.

**Describe the solution you'd like**
change default behavior of qsv   to  not to connect to github to check for updates.

**Describe alternatives you've considered**

**Additional context**
just to expand on usecase -- Another point is that - shall the qsv have breaking feature or an crash bug there'd be many broken instances to fix.  Sofar qsv is super stable, no crashes.

Also the qsv does not change (daily, hourly) that would uphold for the update checks with each execution (hundreds/thousands per day)

**Comment by jqnatividad** [comment]
Hi @slonyik ,
To clarify, qsv only does an auto-update check when:
* it is called without any parameters
* the --update option is used

It does not check every time its invoked.

At this stage, where we have at least one release per week, I'd prefer to keep it on by default until  we reach version 1.0 - when the release tempo should slow down a bit.

That's why I added the QSV_NO_UPDATE environment variable for folks who prefer to pin down their qsv version.

Though there is a version with the self-update engine disabled - `qsvdp`, as it is used by another system (Datapusher+) as an internal component - though it is feature limited and only has commands relevant to Datapusher+.

What I'll do for now is add another feature flag - `no_self_update`, so you can build qsv from source with the self-update engine disabled, but with qsv's full feature set.

**Comment by slonyik** [comment]
Thanks for clarifying the conditions under which qsv does the update and for the config option !

**Comment by slonyik** [comment]
Just compiled the qsvlite using `cargo build --release --features lite` and ran ` ./target/release/qsvlite` and it did not check/connect for updates 👍  :-)

Thank You Joel! 

Just a note - the `-u`  option now reports: 
```
root@4605de40f3d4:/qsv# ./target/release/qsvlite -u
Self update engine disabled.
root@4605de40f3d4:/qsv#
```
This is ok with me. 
Others might expect -u to (force) and update check.🤷‍♂️

**Comment by jqnatividad** [comment]
Good to know qsv fits your security reqts. now...

As for the -u option forcing an update - that's a valid point.  I'll change it for the next release...

**Comment by jqnatividad** [comment]
@slonyik just a heads up, apart from restoring the --update option as you suggested, I also made self-update "smarter" 😉 

https://github.com/jqnatividad/qsv/pull/493
