### ISSUE TITLE
[BUG] No/Wrong pre-built binaries

### ISSUE THREAD

**Issue by Prid13** [jqnatividad/qsv#511]
[v0.68.0](https://github.com/jqnatividad/qsv/releases/tag/0.68.0) doesn't have prebuilt binaries -- is this intended? I'm quite new to qsv, but I'm absolutely loving the maintainer, the quick development, and the pure passion for making this ⭐

[v0.67.0](https://github.com/jqnatividad/qsv/releases/tag/0.67.0)'s `qsvnp.exe` in `qsv-0.67.0-x86_64-pc-windows-msvc.zip` _requires_ Python despite the "np" suffix suggesting it shouldn't 😅

**Comment by jqnatividad** [comment]
Hi @Prid13 ,
Thanks for the kind words! 😊 

And yeah, there were some packaging issues with the previous release that I had to sort out, that's why there were no prebuilt binaries for 0.68.0.

Can you give 0.69.0 a try and let me know?

**Comment by jqnatividad** [comment]
@Prid13 closing this as we are now publishing binaries again with 0.69.0. 

Feel free to create a new issue if there are addl problems you encounter with the new version.

**Comment by Prid13** [comment]
Hi @jqnatividad -- sorry for a bit late response, procrastinated testing those files 😅

**GNU** version of 0.69.0 works great, but the **MSVC** version spits out this error when running `qsvnp`:

> The code execution cannot proceed because python310.dll was not found. Reinstalling he program may fix this problem

![image](https://user-images.githubusercontent.com/27897747/193167832-5134f80c-79ed-47e0-ad88-32295c7b93d8.png)

Not sure it has anything to do with this, but I've got Python 3.7.3 installed on my computer. But QSV _no python_ shouldn't check for that at all, right? 😅

----

I really have you applaud you and everyone else who's working on this project. The sheer amount of tools and utilities that this thing ships, and the amount of tweaks and options it has, it's insane!! Although I don't always find the exact tools I want, the huge number of alternative ways of doing things and the flexibility of them, and the vast amount of knowledge displayed and documented, I just keep having positive experiences with this wonderful tool. Great, freaking, job 👏👏

**Comment by jqnatividad** [comment]
Thanks again @Prid13 for the follow-up bug report and the very kind words.

qsv's ambition (if you have a goal, might as well shoot for the moon, right? 😉 ) is to be the coreutils of CSV, so expect even more functionality in the coming months.

Of course, it wouldn't have been possible without the awesome foundation of xsv from which qsv was forked and the initial bunch of pending PRs which jumpstarted the qsv feature train.

I'll look into why qsvnp.exe is panicking with that error. Like you said, qsvnp shouldn't be linked at all with python...

**Comment by jqnatividad** [comment]
And this is what I love about open source! 

Folks of the same feather, self-selecting, and appreciating and often contributing to the work, not because they have to, but because they want to. 😄 

IMHO, programming is a craft that is best fueled with passion, and I was just lucky enough that working on this project is at the intersection of commercial work we're doing after I stumbled on xsv myself two years ago, with me scratching an itch and making some changes, and getting nominated by some folks to [create a renamed xsv fork with the blessing of the original creator](https://github.com/BurntSushi/xsv/issues/267).

As for supporting the work - just wait a month or two and there will be some news on that front... 😉
