### ISSUE TITLE
BUG fetch/fetchpost ignores http in url parameter

### ISSUE THREAD

**Issue by andrejohansson** [jqnatividad/qsv#543]
**Describe the bug**
In the examples of fetchpost and fetch, I should be able to specify an url directly (starts with http) eg:

```
 qsv fetchpost https://webhook.site/5f2e3c2e-ee4c-41dd-b745-94d2166c7d7c ....
```
Instead of entering an url column. But it doesn´t seem to work. If I put the same url on every entry in the csv file, it works.

**Expected behavior**
My requests to be sent.

**Screenshots/Backtrace/Sample Data**

```
Expected end of field but got '-' instead.
``` 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - qsv Version 0.69.0

**Comment by jqnatividad** [comment]
Thanks for the report @andrejohansson.

Have you tried using the  fetch `--url-template` option? That's what it was meant to do - be able to specify the URL on the command line with the added flexibility of being able to dynamically use CSV row values in the URL itself.

https://github.com/jqnatividad/qsv/blob/b494e34875726c3d3fc0c9a40d63287bf8d6e3fa/tests/test_fetch.rs#L103-L130

It's not available in `fetchpost` as the thinking was it was going to be used primarily for passing URL parameters...

**Comment by andrejohansson** [comment]
Hmm, I did not know about the url template parameter, I was trying to follow the example shown here:
https://github.com/jqnatividad/qsv/blob/6353baa9bf5f58332d3fd138faf776f0d4f5ef90/src/cmd/fetchpost.rs#L55

**Comment by jqnatividad** [comment]
For the `fetchpost` example, it presumes that you created the `form.jql` file, containing the text`"form"`; and `data.csv`.

https://github.com/jqnatividad/qsv/blob/6353baa9bf5f58332d3fd138faf776f0d4f5ef90/src/cmd/fetchpost.rs#L29-L33

I'm attaching both files here for your reference. I have to zip em coz GitHub only accepts certain file formats as attachments.

[fetchpost-example.zip](https://github.com/jqnatividad/qsv/files/9769274/fetchpost-example.zip)

With both files in place, the example you mentioned should work as expected.

**Comment by jqnatividad** [comment]
I also expanded the `fetchpost` example in https://github.com/jqnatividad/qsv/commit/47f7debfe965df823baaf2e71e3dfaae56f6dd55 to explicitly show the form.jql file.

**Comment by andrejohansson** [comment]
Your example works, but I still down follow how the jql file relates to the urls...a bit unclear to me :-)

This is whats tripping me up: 

https://github.com/jqnatividad/qsv/blob/6353baa9bf5f58332d3fd138faf776f0d4f5ef90/src/cmd/fetchpost.rs#L74

>   <url-column>               If the argument starts with `http`, the URL to use.
                               Otherwise, the name of the column with the URL.

**Comment by jqnatividad** [comment]
The thinking here is that in the majority of cases, when doing an HTTP Post, you're using the same static URL for the entire CSV (as the data is passed in the request body, unlike `fetch`, which uses HTTP Get, where the data is passed as part of the URL using query strings ), so if the <url-column> parameter starts with the prefix "http", we use it as "the URL to use."

Otherwise, if the <url-column> parameter doesn't start with literal "http", we use it to select the column to use as the URL in the CSV.

I tried to illustrate this in the usage text, showing how you can call `fetchpost` with the URL column as part of the CSV:

https://github.com/jqnatividad/qsv/blob/98b74a14d3e22badc66231f6b71f017b17340c96/src/cmd/fetchpost.rs#L37

And then following that with an alternative example:

https://github.com/jqnatividad/qsv/blob/98b74a14d3e22badc66231f6b71f017b17340c96/src/cmd/fetchpost.rs#L55

Looking at it now, I "overloaded" the alternative example, as I also show using column index for the <column-list> argument and how the jql selector can be passed with the `--jqlfile` option.

If you can suggest alternate phrasing or a more illustrative example in the `fetch`/`fetch post` usage text, that'd be great!

**Comment by jqnatividad** [comment]
@andrejohansson , closing this issue for now as you can actually specify the URL value itself on the commandline, not just the column from which to fetch it as discussed above.

But I see your point that the usage text can be clearer and I've made some changes that I hope makes it so. If you can suggest some alternate phrasing, please do not hesitate to submit a PR.

**Comment by andrejohansson** [comment]
Thank you for your time explaining, I think we can close this as I did understand how it was intended to be used.
