### ISSUE TITLE
Diff two CSVs

### ISSUE THREAD

**Issue by dufferzafar** [jqnatividad/qsv#547]
**Is your feature request related to a problem? Please describe.**
I usually need to see the data that has changed between two CSVs

**Describe the solution you'd like**

`qsv diff l.csv r.csv` should show the differences between the two CSVs.

**Describe alternatives you've considered**

There is a golang based tool that can do this: [csvdiff
](https://github.com/aswinkarthik/csvdiff)

There is also a git-like flow for CSV files: [wrgl](https://github.com/wrgl/wrgl)

**Additional context**
@janriemer has a library that can do the diffing: https://gitlab.com/janriemer/csv-diff

But for a CLI they want to incorporate it into qsv itself, which I think is a wise choice - since I already use qsv for all other csv needs: https://gitlab.com/janriemer/csv-diff/-/issues/5

**Comment by janriemer** [comment]
Hey @dufferzafar,
thank you for the mention. :slightly_smiling_face: 

This really motivates me to make a first non-alpha release (0.1.0) of `csv-diff` and trying to incorporate it into `qsv`!
There is still a [fairly huge MR open in `csv-diff`](https://gitlab.com/janriemer/csv-diff/-/merge_requests/12), but we are almost there!

I haven't really looked into `qsv` internals yet, but this will also be a great test on how useful/generic as a library `csv-diff` actually is. If it turns out that the interfaces don't fit, we will have to make them fit, which in turn will improve the design of the library itself, so win-win. :slightly_smiling_face: 

Diffing csv's seems to be a highly requested feature in general (looking at xsv's open issues):
https://github.com/BurntSushi/xsv/issues/210

What I want to say is: I'm very keen on trying to implement a first prototype of this. I'll keep you in the loop (hopefully not an endless one :wink:)

### Concerns
My biggest worry is the following: `qsv` seems to put great emphasis on __composing different operations with each other__. At the moment I'm not quite sure yet, how the composition of a diff result can look like in this context.
Maybe one can say: _"Give me all the records that are marked as [`Delete`](https://docs.rs/csv-diff/0.1.0-alpha/csv_diff/diff_row/enum.DiffByteRecord.html#variant.Delete) between csv1 and csv2 and [`concat`](https://github.com/jqnatividad/qsv/blob/master/src/cmd/cat.rs#L2) them to this other csv3"._

So if we integrate this, there needs to be some sort of filtering possible in `qsv` regarding the [diff result of `csv-diff`](https://docs.rs/csv-diff/0.1.0-alpha/csv_diff/diff_row/enum.DiffByteRecord.html).

I've probably missed a lot of other details, but we will get to those eventually. :wink:

**Comment by jqnatividad** [comment]
Thanks @dufferzafar for the request and @janriemer for jumping in!

And you're correct @janriemer, composability is one of the main goals of qsv, but I don't think it dilutes the value proposition of diff as a standalone qsv command.

Composability, IMHO, is a bonus feature, and if we can do as your example above, it'd be awesome, but as they say - the "[perfect is the enemy of good.](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good)"

I look forward to your PRs! 😄

**Comment by janriemer** [comment]
Thank you @jqnatividad for the encouragement. :slightly_smiling_face: 

> Composability, IMHO, is a bonus feature, and if we can do as your example above, it'd be awesome, but as they say - the "[perfect is the enemy of good.](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good)"

I really like this attitude. :wink: Incremental improvement with fast feedback cycles is the way to go! :+1: 

I hope, we can get to a very basic MVP at the end of next month or so (:crossed_fingers:). I'll give you an update here, when I have a rough idea on how to integrate `csv-diff` here.

Really looking forward to collaborating with you on this! :slightly_smiling_face:

**Comment by Prid13** [comment]
I've been using Qsv for the exact same reason as a client wanted to diff two excel files and return only changed/unique rows, and I went the route of converting those excel files to csv first and then using qsv's power commands to extract changed and unique rows only with the help of Lua, and output the results into a new csv file.

This is how I solved it with existing commands on Windows using a Batch file:

1. Join the two csv files into one based on a primary column (this will append the columns of the latter file into the extracted colums of the former csv file where the ID is the same, thereby doubling the column count):
`qsv join ID after.csv ID before.csv`
2. Use Lua to run a script that loops through each row and marks rows where _any_ difference is found between the left half and the right half of columns (the columns from the two files will have been merged by the `join` command, so first half would represent columns from first file, and the second half from the second file):
`qsv lua map Changed -x "local len=math.floor(#col/2); for i=1,len,1 do if(col[i] ~= col[i+len]) then return true; end end return false"`
<sub>Notes: 1) `#col` gives the column count -- 2) column index starts at 1, not 0</sub>
This will create a new column at the end called `Changed`, containing the value of either `true` or `false`
3. Go through all the rows again and only keep rows where the `Changed` column has the value of `true`:
`qsv lua filter "col['Changed'] == 'true'"`
4. Get the column count of one of the csv files (assuming both have equal number of columns) (will be used in next step):
`qsv headers before.csv | qsv count -n`
The number needs to be stored in a variable. Let's assume it's stored in `colsLength`
5. Remove the second half of columns to remove the extra columns (and effectively undo the joining):
`qsv select 1-%colsLength% --output temp.csv`
<sub>Note: `%colsLength%` is Batch-specific syntax</sub>
If the column count is 15, this will select the columns 1 through 15, and skip 16-30 (representing the second file's columns).
The resulting rows will be saved to a new csv file `temp.csv`
6. So far we only have changed rows between the two files. We also need rows with IDs only present in one of the files. For my situation, I only needed the non-joined rows from the _second_ file, so that's what I'm doing here:
`qsv join --left-anti 1 fileAfter.csv 1 fileBefore.csv`
This will perform a 'left anti' join (only return non-matching rows from the _left_ file) on the first columns of each file (`1` represnts the column index to perform the join on, which is the first column in this case)
7. Finally, concatenate the changed rows from before that we saved in the `temp.csv` file, to the unique rows we extracted in the previous step:
`qsv cat rows - temp.csv --output "diffed.csv"`
Save results to a new file `diffed.csv`

Not sure how performant this is, but that's what I landed on for my use case. It's not exactly the kind of diffing you were thinking of (where the changes are shown), but the lua script can be modified to incorporate other stuff easily :)

Here's the batch file I ended up with:

**`script.bat`**
```batch
:: Compares two CSV files and saves any changed rows AND unique rows found in fileAfter into a new file

set fileBefore=.\path\to\file1.csv
set fileAfter=.\path\to\file2.csv
set colsLength=0

:: Get columns count
for /f %%i in ('qsv headers "%fileBefore%" ^| qsv count -n') do set colsLength=%%i

:: Join CSV files, find changed rows and mark them, filter out non-changed rows, save to temp.csv
qsv join ID "%fileAfter%" ID "%fileBefore%" ^
 | qsv lua map Changed -x "local len=math.floor(#col/2); for i=1,len,1 do if(col[i] ~= col[i+len]) then return true; end end return false" ^
 | qsv lua filter "col['Changed'] == 'true'" ^
 | qsv select 1-%colsLength% --output temp.csv

:: Get non-matching rows present in fileAfter only, and concatenate them with the results from above
qsv join --left-anti 1 "%fileAfter%" 1 "%fileBefore%" ^
 | qsv cat rows - temp.csv --output "diffed.csv"

:: Delete the temp file
if exist temp.csv del temp.csv
```

Sorry for long post. Not sure how helpful this is, but wanted to chime in with my 2 cents as this is the exact scenario I've been using Qsv for and struggled a lot to get to a working solution 😇

**Comment by jqnatividad** [comment]
Awesome stuff @Prid13 !

You really exercised qsv there and I'm glad it's working for you.

How's the performance like? Can you share some metrics?

Also, it'd be great if you can share your "recipe" in the Wiki and/or Discussions!

**Comment by janriemer** [comment]
Very cool @Prid13 ! Thank you for sharing. :+1: 

I think this will help people a lot until we can integrate the diffing natively in qsv itself.

**Comment by jqnatividad** [comment]
@janriemer, @Prid13 's 7-step qsv diff pipeline is by itself a big reason why we need a native `diff` command powered by your library 😉

**Comment by janriemer** [comment]
I've just received the "stale issue message" notification and I want to let you know that I'm actively working on this.

Integration of `csv-diff` works great so far! Codebase of `qsv` is very easy to understand and very maintainable. :+1: 

I'll probably give another more detailed update in like 8h or so, but just this much:
We __will__ have a first working MVP of `diff` in `qsv` before the holidays! :santa:

**Comment by janriemer** [comment]
### Comparing 1,000,000 rows of CSV in less than 800ms :tada: 

Comparing 1,000,000 rows of CSV in _less than 800ms_ :tada: This is probably now the fastest CSV differ in the world! :rocket:   
I haven't done any memory/RAM benchmarks yet, but looking at my system monitor it seems to stay under 150mb. 🍃

#### See this gist for the svg recording of me executing the new `diff` command in the terminal (for some strange reason, I'm unable to embed it directly here):
https://gist.githubusercontent.com/janriemer/0e86a236a7174af6faed1b981815a5ea/raw/2ab235a2bdd5798f2348d42da48fdda276fb5f0f/qsv_diff_recording.svg

It compares the [Majestic Million CSV](https://blog.majestic.com/development/majestic-million-csv-daily/), which has one million rows with 12 columns. I've changed the 4th row and deleted some other rows.

The diff result can be seen in the first column (whether it should stay this way is open for debate):
- "-" means that the record was **deleted** in the file on the right (can be seen after the first two records in the recording)
- "+" means that the record was **added** in the file on the right (the recording doesn't show this type of change)
- consecutive "-", "+" means the record was modified in some columns that were not key columns (this can be seen in the first two rows of the recording)

I'll write a follow up on this in the coming days. Topics will be:
- current limitations
- what needs to change in qsv itself (spoiler: it is _very_ little and all tests of course are still passing after I've made the change!)
- listing the next steps to get to an MVP

Next steps will be:
- Writing tests!
- Open a PR, so that you can provide an initial review and things I can improve :slightly_smiling_face:

**Comment by jqnatividad** [comment]
Awesome news @janriemer !!!

I can't wait for your PR! It'd be a great holiday gift for us data geeks!!!

**Comment by janriemer** [comment]
@jqnatividad I'm sorry, but I won't make it until the holidays. :cry: 
Tomorrow, I'll be on vacation for a week, so I'll probably continue working on this end of this year/start of next year.

I'm sorry for the false promises, but I'd rather not rush this and have a proper PR you can review.

Anyway, I wish you pleasant holidays! :slightly_smiling_face:

**Comment by jqnatividad** [comment]
Thanks for the heads-up @janriemer ! I was actually holding up the release of 0.80.0 in anticipation of your initial `diff` PR...

I'll just release it then to tide us over data geeks, as we look forward to your `diff` 🎁 next year!

Happy Holidays! ⛄ 🎄 😃

**Comment by janriemer** [comment]
@jqnatividad Thank you for your patience and considerations.

[The PR has just been created](https://github.com/jqnatividad/qsv/pull/711) :tada: => #711 

Please don't hesitate to ask any questions. I'll try to answer them as soon as I can (although I have to admit: I'm a little intimidated by the frequency you push out new releases :laughing: I can barely keep up with this kind of pace :wink: ).

Heads-up @dufferzafar @Prid13 :slightly_smiling_face: :eyes:

**Comment by jqnatividad** [comment]
Woohoo!!! A Happy New Year indeed with this much needed command!

Thanks @janriemer !

I'll start reviewing it tonight and will post my comments on the PR.

And don't be intimidated by the frequency of releases - qsv, fortunately for me, sits at the intersection of work+passion+hobby. 🧑‍💻 + ❤️ + 🎮 

It started out as a side project, spurred by a project I was working on at the time; then as a way to learn Rust; and now, as a central differentiator for the CKAN-related Data Engineering work we're doing at the company, further accelerated by several key client projects that drive features into the backlog.

It's only further accelerated by folks like you that discover qsv - adding more use cases, feature requests, and new commands that further increase the tempo of releases. 😄 

So yep - I'm addicted 😉

**Comment by janriemer** [comment]
@jqnatividad 
> And don't be intimidated by the frequency of releases - qsv, fortunately for me, sits at the intersection of work+passion+hobby.
>
>It started out as a side project, spurred by a project I was working on at the time; then as a way to learn Rust; and now, as a central differentiator for the CKAN-related Data Engineering work we're doing at the company, further accelerated by several key client projects that drive features into the backlog.

This is really cool that you can work on it as part of your job! :+1: Thank you for sharing your story - this is very inspiring! :sparkles:
