### ISSUE TITLE
Add MySQL support and generate SQL script instead of/in addition to connecting

### ISSUE THREAD

**Issue by ondohotola** [jqnatividad/qsv#687]
**Is your feature request related to a problem? Please describe.**
I like the news PostgreSQL and SqlIte support, so of course one would like MySQL/MariaDB as well.

I would (sometimes) like to be able to read the SQL script produced before connecting and adding.

**Describe the solution you'd like**
As above.

**Describe alternatives you've considered**
Nil

**Additional context**
Nil.

**Comment by jqnatividad** [comment]
Sounds like a good idea @ondohotola … what do you think @kindly ?

**Comment by kindly** [comment]
@ondohotola @jqnatividad 

I am not an expert with mysql as I have not used it in 15 years! which is why this is not done. For both sqlite and postgres, I understand the common connection patterns, and the quickest ways to insert data, but I am uncertain of doing a mysql option well.  If I had some guidence on this, then that would be great.  

A dry run option makes sense.  It probably would not have all the `insert statements` as for big datasets that could potentially be massive.  However, it should show the table create/alter statements and the `copy` statements for postgres and the `prepared statement` for sqlite (i.e the template for all the insert statements).

**Comment by jqnatividad** [comment]
Most of my db work is with Postgres as well, and I've not used MySQL/MariaDB of late.

A quick search on crates.io yields https://github.com/blackbeam/rust-mysql-simple.

The common usage patterns of a connection string, and MySQL's [LOAD DATA](https://dev.mysql.com/doc/refman/8.0/en/load-data.html) statement (similar to Postgres COPY) suggest that perhaps Postgres/MySQL can share some common code, perhaps, by introducing a dialect option?

Regardless, however you decide to support MySQL/MariaDB, I would put it behind a feature flag.

And yes, dry run does make sense though you may still want to give the user the option to create all the insert statements, with a sensible default of having a small sample.

**Comment by kindly** [comment]
In https://github.com/jqnatividad/qsv/pull/736 there is now an option to produce a dump file instead of providing a connection.  This gives you esentailly the SQL script that will be used if you run it against the database directly.

I have looked into mysql support and it is a lot more complicated that I can do for quite a while.  The `load data` command only works if the server is configured to accept local files, so will not work consistantly.

**Comment by ondohotola** [comment]
`load data LOCAL infile` should always work...

**Comment by kindly** [comment]
@ondohotola 

That is not my reading of https://dev.mysql.com/doc/refman/8.0/en/load-data-local-security.html
