### ISSUE TITLE
to and stat comment: field inferencing not coherent

### ISSUE THREAD

**Issue by aborruso** [jqnatividad/qsv#688]
Hi,
if I transform [this CSV](https://dati.mit.gov.it/scp/v_od_bandi.csv) in parquet using `to`, I have that the `luogo_esecuzione_istat` field is mapped as `integer` in the output parquet file. 

This is wrong, it's a string, and it's properly mapped as string using `stats`.

I think that `to` command should use the same field inferencing of `stats`.

Thank you

**Comment by jqnatividad** [comment]
Thanks for the report @aborruso .

As for `to` type inferencing not being consistent with `stats`, its because I recently added leading zero handling here @kindly 

https://github.com/jqnatividad/qsv/blob/7844e0c8e90d3ba1f4ff1932e54e7b4bc3bffd43/src/cmd/stats.rs#L825-L840

Perhaps, `csvs_convert` should do the same?

**Comment by kindly** [comment]
@aborruso @jqnatividad yep this is sensible we fix it soon.
