### ISSUE TITLE
`diff`: Explore using Frictionless Data Tabular Diff Format

### ISSUE THREAD

**Issue by jqnatividad** [jqnatividad/qsv#733]
Hi @janriemer,
Have you considered using the [Tabular Diff Format](https://specs.frictionlessdata.io/tabular-diff/#language) for the diffresults?

It's quite comprehensive and tailor-made for diffing tabular data.  Maybe we can even use [`daff`](https://github.com/paulfitz/daff) to render the diffresults into HTML...

**Comment by janriemer** [comment]
Hey @jqnatividad 
oh yes, this looks really neat, thank you for the pointer and suggestion. 👍

No, I haven't looked into this, but I remember seeing it being mentioned in the [issue thread about diffing over at xsv](https://github.com/BurntSushi/xsv/issues/210).

Anyway, I've created [an issue over at `csv-diff`](https://gitlab.com/janriemer/csv-diff/-/issues/13) for it ("lucky issue number 13"😄), because I think it is a really good suggestion and very useful!

As mentioned in the linked issue, we first need to get [_Consider ordering of columns when both CSVs have headers_](https://gitlab.com/janriemer/csv-diff/-/issues/3) resolved in `csv-diff`. This will be one step to more _flexibility_ in `csv-diff` as a whole and will probably also allow further improvements like _ignoring entire columns_ during diff, which we can then also implement in `qsv`.

Thank you for the suggestion! ❤️ 

------------------------------------------
### Off-topic
Sorry for not having finished the other implementation in #714 yet. 😢 I don't want to make any more false estimates on when I will have fixed it, but I should be able to take some time during the weekend.

Thank you for being patient with this. 🙇 

I think, we have so many ideas for `diff` and `csv-diff`, but not enough time or energy to implement them, which makes me really sad. 😢

**Comment by jqnatividad** [comment]
No apologies required @janriemer , `diff` is a great addition to qsv and any time you can spare is most appreciated!

As for ignoring columns, have you looked at leveraging the built-in [`select` helper](https://github.com/jqnatividad/qsv/blob/master/src/select.rs) in qsv?  Similar to the dedicated `select` command, it's used by several commands to offer `--select` as an option.

**Comment by janriemer** [comment]
Thank you for your kind words! :heart: 

No, I haven't looked at the `select` helper, but that looks like it's the exact thing we'll need to implement something like ignoring columns. Thank you for the pointer. :+1:
