### ISSUE TITLE
`qsv to parquet` freezes when reading from a Linux named pipe.

### ISSUE THREAD

**Issue by derekmahar** [jqnatividad/qsv#779]
`qsv to parquet` freezes when reading from a Linux named pipe.  Reading from a named pipe instead of a file is useful in cases where the CSV input data is very large and must be transformed by other commands in a shell pipeline before converting the input to a Parquet file.

Actual behaviour:
```
$ mkfifo qsv_fifo.csv
$ printf "letter,number\na,1\nb,2\nc,3\n" > qsv_fifo.csv &
[1] 441056
$ qsv to parquet output qsv_fifo.csv
```
`qsv to parquet` hangs attempting to read from named pipe `qsv_fifo.csv`, presumably waiting for the named pipe to receive input data.  However, the previous `printf` process had already sent input data to the named pipe and is waiting for a reader.

Expected behaviour:

`qsv to parquet` reads the CSV data from named pipe `qsv_fifo.csv` and creates Parquet file `output/qsv_fifo.parquet`, just like it does when it reads from a CSV file:

```
$ cat --plain test.csv
letter,number
a,1
b,2
c,3
$ qsv to parquet output test.csv

Table 'test' (3 rows)

Field Name  Field Type  Field Format
letter      string      string
number      integer     integer

$ find output/
output/
output/test.parquet
```

Note that `qsv cat rows` can read from the named pipe:
```
$ printf "letter,number\na,1\nb,2\nc,3\n" > qsv_fifo.csv &
[1] 442337
$ qsv cat rows qsv_fifo.csv
letter,number
a,1
b,2
c,3
[1]+  Done                    printf "letter,number\na,1\nb,2\nc,3\n" > qsv_fifo.csv
```

Test script:
```
mkfifo qsv_fifo.csv
printf "letter,number\na,1\nb,2\nc,3\n" > qsv_fifo.csv &
qsv to parquet output qsv_fifo.csv
```

System details:
 - Ubuntu 22.04.1 LTS
 - qsv 0.88.2

**Comment by derekmahar** [comment]
`qsv to sqlite` also freezes when attempting to read from a named pipe, so this may be a more general issue with `qsv to`:

```
$ printf "letter,number\na,1\nb,2\nc,3\n" > qsv_fifo.csv &
[1] 444033
$ qsv to sqlite output.sqlite qsv_fifo.csv
```

**Comment by jqnatividad** [comment]
Thanks for the detailed report @derekmahar . 

One of qsv's primary design goal is to be composable, so I can certainly see making it work with named pipes, but as you surmised, I haven't done any testing using named pipes.

Do named pipes work with other qsv commands?

Any thoughts @kindly ?

**Comment by derekmahar** [comment]
> Do named pipes work with other qsv commands?

Yes, as I mentioned in the issue description, `qsv cat rows` can read named pipes.  I have also just verified that `qsv headers` and `qsv sort` can read from a named pipe.

**Comment by kindly** [comment]
@derekmahar @jqnatividad 

I am not sure this can be made to work without a lot of effort and other downsides.

The issue is that the `to` commands analyze the whole file before converting them into the other formats.  This is because its design is to make certain that the load will not fail in as many cases as possible.
The most common failure comes if it the types that are expected are wrong.  For Parquet and SQL dbs you need to specify the types upfront, and they are strict with types, and will fail if incorrect.
The the above issue comes from trying to read the file and then seeking back to the start, which is impossible with a (named) pipe.

The solutions I can think of are:

1.  To sample the top of the file when it comes in (which is frequently goes wrong in my experiance as lots of files are not consistant)  and is tricky to implement.
2.  To give the users a way to specify the types at their own risk and fail if they get it wrong.  This may be possible as a datapackage could be used as an input, and it would be upto the users to generate one based on their own sampling or by upfront analysing the whole file.  csvs_convert allows a datapackage input which will not seek.
3.  For streaming/pipes just default all fields at Strings (not great).
4.  Chunk the stream into say 10000 rows and for each save the stream to disk producing seperate parquet files for each chunk, risking the fact that each parquet files could have incompatable types.

My preference is 2, but it places a high burden on the user to get it correct.  The aim of the library was to make the conversions as simple as possible, at the expense of disk space!

You could try https://github.com/domoritz/arrow-tools/tree/main/crates/csv2parquet, but from my reading of the code is that it has the same issue, as even though it uses the sampling approach (1) it does not store the sample data in order to convert it so also seeks to the start of the file.  It does allow specifying a schema upfront though.




-

**Comment by redviking1** [comment]
I would also prefer option 2, but I think options 2 and 3 should also be available.

**Comment by derekmahar** [comment]
For comparison, DuckDB 0.6.1 can read CSV data from a named pipe and write it to a Parquet file without having to specify the column types:

```
$ cat test.csv > test_fifo.csv &
[1] 563428
$ duckdb -c "COPY (SELECT * FROM read_csv_auto('test_fifo.csv')) TO 'test.parquet' (FORMAT PARQUET)"
[1]+  Done                    bat test.csv > test_fifo.csv
$ duckdb -c "SELECT * FROM 'test.parquet'"
┌─────────┬────────┐
│ letter  │ number │
│ varchar │ int32  │
├─────────┼────────┤
│ a       │      1 │
│ b       │      2 │
│ c       │      3 │
└─────────┴────────┘
```
This command "streams" the CSV data from the input source to the output target, so it does not consume any intermediate persistent storage.

My guess is that to determine the column types, DuckDB reads and samples some number of initial rows, though in this case it probably read the entire input stream since it is small.

**Comment by kindly** [comment]
@derekmahar duckdb definately samples some amount of the file, to first get the types.  It has a SAMPLE_SIZE option for CSV loading https://duckdb.org/docs/data/csv#parameters.  It says it samples random parts from input file, but I imagine it only does that for input sources that are seekable, and otherwise takes the first 1024 lines.

Funnily enough, this was one of the reasons for writing the parquet conversion, as I work with messy data normally.  I tried it with duckdb for the data pipeline I was working on, but I had to feed `read_csv` with the types upfront in order to make it work.

I was close to makeing a little python command line tool that wrapped an in memory duckdb database for conversion tasks like this, and the rate that duckdb is improving, it might a sensible option.   Also could do this rust and embed a version of duckdb.

 Its only other downside is the duckdb type detection is not great for dates and I think if you have the SAMPLE_SIZE to -1 it loads the whole file to memory.  However, that could have changed as they are doing lots of work to contrain memory size and put more stuff on disk when needed.

I will look into option 1 as I have not worked out how difficult it would be. if I was allowing for failure but would be an extra option and not default behaviour, something like a `stream` option.

**Comment by derekmahar** [comment]
> Funnily enough, this was one of the reasons for writing the parquet conversion, as I work with messy data normally. I tried it with duckdb for the data pipeline I was working on, but I had to feed `read_csv` with the types upfront in order to make it work.

Why did you not like having to specify the column types in `read_csv`?

> I was close to makeing a little python command line tool that wrapped an in memory duckdb database for conversion tasks like this, and the rate that duckdb is improving, it might a sensible option. Also could do this in rust and embed a version of duckdb.

`qsv` could benefit from [duckdb-rs](https://github.com/wangfenjin/duckdb-rs), a Rust wrapper around the DuckDB library.  `qsv to` might even use it to convert CSV input data to a DuckDB database!


> Its only other downside is the duckdb type detection is not great for dates and I think if you have the SAMPLE_SIZE to -1 it loads the whole file to memory. However, that could have changed as they are doing lots of work to contrain memory size and put more stuff on disk when needed.

Have you encountered any particular cases where DuckDB `read_csv_auto` is unable to parse a date, time, or time stamp?  DuckDB has some sophisticated [rules](https://duckdb.org/docs/data/csv/auto_detection#dates-and-timestamps) for date and time auto-detection and `read_csv` provides the `dateformat` and `timestampformat` options for ambiguous or obscure date and time formats.
 
> I will look into option 1 as I have not worked out how difficult it would be, but would be an extra option and not default behaviour.

Yes, I think this makes sense.

**Comment by derekmahar** [comment]
Does [csvs_convert](https://github.com/kindly/csvs_convert) always read the entire CSV file contents when it converts it to a Parquet file?  What other tools do you use in your data pipeline?

I look forward to the DuckDB storage format becoming stable.  It's inconvenient and takes a lot of disk space to export a large database each time you upgrade to a new DuckDB minor version.

**Comment by kindly** [comment]
> Does [csvs_convert](https://github.com/kindly/csvs_convert) always read the entire CSV file contents when it converts it to a Parquet file? 

Not when you supply it a datapackage with the types in it.

> What other tools do you use in your data pipeline?

The other main tool I use, is another one I wrote, https://github.com/kindly/flatterer 

It converts deeply nested JSON to tabular representation and uses csvs_convert underneath. It creates the datapackage itself and does the type detection when reading the JSON.  Adding an option to QSV to supply a datapackage (option 2 above) would be helpful in this case.

Having thought about the above, `csvs_convert` currently uses apache arrow rust parquet library underneath to do the conversion to PARQUET.  I have never been too happy with it.  I am wondering if I should just embed duckdb instead and supply it the types guessed instead of using an in memory db.   This would mean that a streaming option would be easy.

**Comment by derekmahar** [comment]
> Not when you supply it a datapackage with the types in it.

Today I learned about the [datapackage](https://specs.frictionlessdata.io/data-package/) standard!  (By the way, the link to [Data Package format](https://datahub.io/docs/data-packages) is broken on [Tabular Data Packages](https://datahub.io/docs/data-packages/tabular).

> The other main tool I use, is another one I wrote, https://github.com/kindly/flatterer

I tend to use more CSV than JSON data, but as I encounter more JSON, I'll keep [flatterer](https://github.com/kindly/flatterer) in mind!

> Having thought about the above, `csvs_convert` currently uses apache arrow rust parquet library underneath to do the conversion to PARQUET. I have never been too happy with it. I am wondering if I should just embed duckdb memory db instead and supply it the types guessed instead. This would mean that a streaming option would be easy.

How common and useful is [Apache Arrow](https://arrow.apache.org/) in data science?

**Comment by kindly** [comment]
@derekmahar

For this I only used arrow as it looked like it was the best native parquet library for rust.  arrow and parquet formats, as far as I understand, match in many places.
